package com.quizz.entities;
// Generated Feb 25, 2025, 3:51:45 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * UserAnswers generated by hbm2java
 */
@Entity
@Table(name = "user_answers")
public class UserAnswers implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "user_answer_id", unique = true, nullable = false)
    private Long userAnswerId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "answer_id", nullable = false)
    private Answers answers;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "question_id", nullable = false)
    private Questions questions;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "attempt_id", nullable = false)
    private QuizzAttempts quizzAttempts;

    @Column(name = "is_correct", nullable = false)
    private Boolean isCorrect;

    @Column(name = "created_at", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    public UserAnswers() {
    }

    public UserAnswers(Answers answers, Questions questions, QuizzAttempts quizzAttempts, Boolean isCorrect,
	    Date createdAt) {
	this.answers = answers;
	this.questions = questions;
	this.quizzAttempts = quizzAttempts;
	this.isCorrect = isCorrect;
	this.createdAt = createdAt;
    }

    public Long getUserAnswerId() {
	return this.userAnswerId;
    }

    public void setUserAnswerId(Long userAnswerId) {
	this.userAnswerId = userAnswerId;
    }

    public Answers getAnswers() {
	return this.answers;
    }

    public void setAnswers(Answers answers) {
	this.answers = answers;
    }

    public Questions getQuestions() {
	return this.questions;
    }

    public void setQuestions(Questions questions) {
	this.questions = questions;
    }

    public QuizzAttempts getQuizzAttempts() {
	return this.quizzAttempts;
    }

    public void setQuizzAttempts(QuizzAttempts quizzAttempts) {
	this.quizzAttempts = quizzAttempts;
    }

    public Boolean getIsCorrect() {
	return this.isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
	this.isCorrect = isCorrect;
    }

    public Date getCreatedAt() {
	return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
	this.createdAt = createdAt;
    }

}
